- hosts: servers
  gather_facts: true
  tasks:
    - name: copy .bashrc
      copy:
        src: "{{ playbook_dir }}/.bashrc"
        dest: "~"

    - name: install software on ubuntu
      when: ansible_distribution == 'Ubuntu'
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - sysstat
          - nmon
    - name: install software on centos
      when: ansible_distribution == 'CentOS'
      become: true
      yum:
        name:
          - net-tools.x86_64
          - telnet
          - epel-release
          - python-pip
          - git
          - sysstat
          - nmon

    - name: fzf download
      git:
        depth: 1
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.fzf
    - name: fzf install
      shell: ~/.fzf/install --all
